[tool.poetry]
name = "shioajicaller"
version = "0.1.0"
description = "shioaj warp caller"
authors = ["Steve Lo <info@sd.idv.tw>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
shioaji = "^0.3.2-alpha.9"
dotenv = "^0.0.5"

[tool.poetry.dev-dependencies]
shioaji = "^0.3.2-alpha.9"
dotenv = "^0.0.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
